@@include("../../blocks/components/tabs-block/tabs-block.js")
@@include("../../blocks/components/multi-menu/multi-menu.js")
@@include("../../blocks/components/period-select/period-select.js")
@@include("../../blocks/components/media-slider/media-slider.js")
@@include("../../blocks/components/form/form.js")
@@include("../../blocks/components/field-file/field-file.js")
@@include("../../blocks/components/video/video.js")
@@include("../../blocks/components/select/select.js")
@@include("../../blocks/components/spoiler/spoiler.js")

document.addEventListener('DOMContentLoaded', () => {
    tabsBlockInit()
    multiMenu()
    periodSelect()
    mediaSlider()
    fileFieldInit()
    validation()
    videos()
    selects()
    spoilers()
})